package com.example.stockit.controller;

import android.content.Context;
import android.util.Log;
import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;
import com.example.stockit.model.AppDatabase;
import com.example.stockit.model.Product;
import com.example.stockit.util.StockItReporter;
import java.util.List;

public class ReportWorker extends Worker {

    public ReportWorker(@NonNull Context context, @NonNull WorkerParameters workerParams) {
        super(context, workerParams);
    }

    @NonNull
    @Override
    public Result doWork() {
        String type = getInputData().getString("REPORT_TYPE");
        String finalType = (type != null) ? type : "DAILY";

        generateAndSendReport(finalType);

        return Result.success();
    }

    private void generateAndSendReport(String type) {
        AppDatabase db = AppDatabase.getInstance(getApplicationContext());
        List<Product> products = db.productDao().getAll();

        StringBuilder csv = new StringBuilder("ID,Name,Quantity,Price\n");
        for (Product p : products) {
            csv.append(p.getId()).append(",")
               .append(p.getName()).append(",")
               .append(p.getQuantity()).append(",")
               .append(p.getUnitPrice()).append("\n");
        }

        sendReportViaWebhook(type, csv.toString(), products.size());
    }

    private void sendReportViaWebhook(String type, String csvData, int count) {
        String message = "Automatic stock report generated by scheduled worker.\n\n"
            + "- Type          : " + type + "\n"
            + "- Items count   : " + count + "\n\n"
            + "CSV content:\n" + csvData;

        StockItReporter.sendReport(
                "StockIT-Worker",
                "wissem.soussia@vista.com",
                "Report " + type,
                message,
                (success, bodyOrError) -> {
                    if (success) {
                        Log.d("ReportWorker", "Report sent via webhook: " + bodyOrError);
                        NotificationHelper.showNotification(getApplicationContext(),
                                "Report sent!",
                                "The report was sent to the StockIT workflow.",
                                777);
                    } else {
                        Log.e("ReportWorker", "Webhook failed: " + bodyOrError);
                    }
                });
    }
}
